name: Liquibase + PostgreSQL CI (using setup-liquibase)

on:
  push:
    branches:
      - main
    paths:
      - 'changelog/**'

jobs:
  liquibase:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Liquibase
        uses: liquibase/setup-liquibase@v1
        with:
          version: '4.32.0'     # pick a version that exists
          edition: 'oss'        # or 'pro' if you have a license

      - name: Run Liquibase Update
        env:
          LIQUIBASE_URL: jdbc:postgresql://localhost:5432/mydb
          LIQUIBASE_USERNAME: myuser
          LIQUIBASE_PASSWORD: mypassword
        run: |
          liquibase \
            --changeLogFile=changelog/db.changelog-master.xml \
            --url=$LIQUIBASE_URL \
            --username=$LIQUIBASE_USERNAME \
            --password=$LIQUIBASE_PASSWORD \
            update

      - name: verify that only one row exists in customers table
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          count=$(PGPASSWORD=mypassword psql -h localhost -U myuser -d mydb -t -c "select count(*) from customers;" | xargs)
          echo "row count: #$count#"
          if [ "$count" -ne 1 ]; then
            echo "expected 1 row, found $count"
            exit 1
          else
            echo "exaclty 1 row found in the customers table, perfect!"
          fi
            
      
      
