name: Liquibase + PostgreSQL (Official Action)

on:
  push:
    branches:
      - main
    paths:
      - 'changelog/**'

jobs:
  liquibase:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Liquibase using official GitHub Action
        uses: liquibase/liquibase-github-action@v4.25.1
        with:
          operation: update
          changeLogFile: changelog/db.changelog.xml
          url: jdbc:postgresql://localhost:5432/mydb
          username: myuser
          password: mypassword
          classpath: /usr/share/java/postgresql.jar
          driver: org.postgresql.Driver
